services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      PORT: "8080"
      REDIS_ADDR: "redis:6379"
      REDIS_DB: "0"
      REDIS_KEY_TTL: "72h"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
